### ISSUE TITLE
`Hive.monad.rBind` is growing the stack

### ISSUE THREAD

**Issue by rowandavies** [CommBank/ebenezer#102]
This may not be an issue in practice, and perhaps this is just normal in Scala, but I was surprised to see 32 consecutive  stack frames for `rBind` in a stack trace (while working on Commbank/maestro#348):

```
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:924)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:914)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anonfun$10$$anonfun$apply$7$$anonfun$11.apply(Hive.scala:288)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anonfun$10$$anonfun$apply$7$$anonfun$11.apply(Hive.scala:288)
	at au.com.cba.omnia.omnitool.Result$.safe(Result.scala:153)
	at au.com.cba.omnia.omnitool.ResultantMonad$$anonfun$point$1.apply(ResultantMonad.scala:37)
	at au.com.cba.omnia.omnitool.ResultantMonad$$anonfun$point$1.apply(ResultantMonad.scala:37)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rPoint$1.apply(Hive.scala:308)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rPoint$1.apply(Hive.scala:308)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive.run(Hive.scala:61)
	at au.com.cba.omnia.maestro.core.scalding.RichExecutionObject$$anonfun$fromHive$1$$anonfun$apply$11.apply(RichExecution.scala:82)
	at au.com.cba.omnia.maestro.core.scalding.RichExecutionObject$$anonfun$fromHive$1$$anonfun$apply$11.apply(RichExecution.scala:82)
	at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1$$anonfun$1.apply(Execution.scala:251)
	at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1$$anonfun$1.apply(Execution.scala:251)
	at scala.util.Try$.apply(Try.scala:161)
	at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1.apply(Execution.scala:251)
```

**Comment by jameshales** [comment]
This doesn't appear to be a problem with your specific monad implementation, but a more general problem with recursive monadic code. The form of Scala's `for` expressions prevents you from placing a recursive call to monadic code in the tail position, so Scala can't perform tail call optimisation on the resultant code. A simple example using the `Option` monad to implement a recursive `subtract` method:

```scala
object MonadTest {
    def subtract(ma : Option[Integer], mb : Option[Integer]) : Option[Integer] = {
        for {
            a <- ma
            b <- mb
            r <- if (b == 0)
                    Some(a)
                 else if (b < 0)
                     None
                 else
                     subtract(Some(a - 1), Some(b - 1))
        } yield r
    }
}
```

Calling `MonadTest.subtract(Some(1000000), Some(1000000))` results in a `StackOverflowException`:

```
scala> MonadTest.subtract(Some(1000000), Some(1000000))
java.lang.StackOverflowError
	at MonadTest$$anonfun$subtract$1$$anonfun$apply$1.apply(Monads.scala:6)
	at MonadTest$$anonfun$subtract$1$$anonfun$apply$1.apply(Monads.scala:5)
	at scala.Option.flatMap(Option.scala:170)
	at MonadTest$$anonfun$subtract$1.apply(Monads.scala:5)
	at MonadTest$$anonfun$subtract$1.apply(Monads.scala:4)
	at scala.Option.flatMap(Option.scala:170)
	at MonadTest$.subtract(Monads.scala:4)
	at MonadTest$$anonfun$subtract$1$$anonfun$apply$1.apply(Monads.scala:11)
	at MonadTest$$anonfun$subtract$1$$anonfun$apply$1.apply(Monads.scala:5)
	at scala.Option.flatMap(Option.scala:170)
	at MonadTest$$anonfun$subtract$1.apply(Monads.scala:5)
	at MonadTest$$anonfun$subtract$1.apply(Monads.scala:4)
	at scala.Option.flatMap(Option.scala:170)
	at MonadTest$.subtract(Monads.scala:4)
	at MonadTest$$anonfun$subtract$1$$anonfun$apply$1.apply(Monads.scala:11)
	at MonadTest$$anonfun$subtract$1$$anonfun$apply$1.apply(Monads.scala:5)
	at scala.Option.flatMap(Option.scala:170)
	at MonadTest$$anonfun$subtract$1.apply(Monads.scala:5)
	at MonadTest$$anonfun$subtract$1.apply(Monads.scala:4)
	at scala.Option.flatMap(Option.scala:170)
	at MonadTest$.subtract(Monads.scala:4)
[...]
```

We can see that Scala cannot perform tail call optimisation on this code because the recursive call is not in the tail position (inside the `yield`) but is necessarily inside the first block of the for comprehension:

```scala
import scala.annotation.tailrec

object MonadTest {
    @tailrec
    def subtract(ma : Option[Integer], mb : Option[Integer]) : Option[Integer] = {
        for {
            a <- ma
            b <- mb
            r <- if (b == 0)
                    Some(a)
                 else if (b < 0)
                     None
                 else
                     subtract(Some(a - 1), Some(b - 1))
        } yield r
    }
}
```

This code doesn't compile.

```
Compiling 1 Scala source to /Users/james/Documents/Monads/target/scala-2.10/classes...
/Users/james/Documents/Monads/Monads.scala:7: could not optimize @tailrec annotated method subtract: it contains a recursive call not in tail position
            a <- ma
                 ^
one error found
(compile:compileIncremental) Compilation failed
Total time: 0 s, completed 10/07/2015 11:38:05 AM
```

Compare this to the Haskell code I would have written for the same function:

```haskell
mySubtract :: Maybe Int -> Maybe Int -> Maybe Int
mySubtract ma mb = do
  a <- ma
  b <- mb
  if b == 0 then
    return a
  else
    mySubtract (Just $ a - 1) (Just $ b - 1)
```

This `mySubtract` will happily work on large values without overflowing the stack. Here the recursive call to `mySubtract` is in the tail position and can be optimised by GHC. Note that the Haskell code contains a `return` (equivalent to a `yield`) inside an `if` expression, and we can call `mySubtract` directly within the `if` expression, without first having to bind it to an intermediate value. It isn't possible to put a `yield` inside an `if` expression in Scala because of its rigid syntax for `for` comprehensions.

It is probably possible to write a tail recursive version of `subtract` by directly using `flatMap`, `filter`, etc.
