### ISSUE TITLE
ParquetScroogeSource throwing NullPointerException if the input directory is empty

### ISSUE THREAD

**Issue by SajeevAr** [CommBank/ebenezer#116]
ParquetScroogeSource is throwing a NullPointerException, if the input directory given for creating the pipe is empty. This scenario has occurred in a sqoop export job where parquet files for export are read from an hdfs directory using ParquetScroogeSource, to create a TypedPipe with TDsl implicit conversions. When the input directory is empty, the job is failing with the following NullPointerException.

15/06/29 16:59:24 INFO util.Version: Concurrent, Inc - Cascading 2.5.5
15/06/29 16:59:24 INFO flow.Flow: [] starting
15/06/29 16:59:24 INFO flow.Flow: []  source: Hfs["ParquetScroogeScheme[[UNKNOWN]->[ALL]]"]["<input_path>"]
15/06/29 16:59:24 INFO flow.Flow: []  sink: Hfs["TextDelimited[[0]]"]["/tmp/ST_128_08_CCA_APP1cb623dc-c1f5-4bcb-a24a-97ba74633b81"]
15/06/29 16:59:24 INFO flow.Flow: []  parallel execution is enabled: true
15/06/29 16:59:24 INFO flow.Flow: []  starting jobs: 1
15/06/29 16:59:24 INFO flow.Flow: []  allocating threads: 1
15/06/29 16:59:24 INFO flow.FlowStep: [] starting step: (1/1) ...f5-4bcb-a24a-97ba74633b81
15/06/29 16:59:29 INFO mapred.FileInputFormat: Total input paths to process : 0
15/06/29 16:59:29 INFO mapred.JobClient: Cleaning up the staging area 
15/06/29 16:59:29 INFO flow.Flow: [] stopping all jobs
15/06/29 16:59:29 INFO flow.FlowStep: [] stopping: (1/1) ...f5-4bcb-a24a-97ba74633b81
15/06/29 16:59:29 INFO flow.Flow: [] stopped all jobs
15/06/29 16:59:29 ERROR car.CseCcaAppExportExecution$: error running execution
java.lang.NullPointerException
	at parquet.hadoop.ParquetInputFormat.getSplits(ParquetInputFormat.java:430)
	at parquet.hadoop.mapred.DeprecatedParquetInputFormat.getSplits(DeprecatedParquetInputFormat.java:48)
	at cascading.tap.hadoop.io.MultiInputFormat.getSplits(MultiInputFormat.java:200)
	at cascading.tap.hadoop.io.MultiInputFormat.getSplits(MultiInputFormat.java:134)
	at org.apache.hadoop.mapred.JobClient.writeOldSplits(JobClient.java:1134)
	at org.apache.hadoop.mapred.JobClient.writeSplits(JobClient.java:1126)
	at org.apache.hadoop.mapred.JobClient.access$600(JobClient.java:178)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:1023)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:976)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1642)
	at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:976)
	at org.apache.hadoop.mapred.JobClient.submitJob(JobClient.java:950)
	at cascading.flow.hadoop.planner.HadoopFlowStepJob.internalNonBlockingStart(HadoopFlowStepJob.java:107)
	at cascading.flow.planner.FlowStepJob.blockOnJob(FlowStepJob.java:196)
	at cascading.flow.planner.FlowStepJob.start(FlowStepJob.java:149)
	at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:124)
	at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:43)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
29/06/2015 4:58:36 PM INFO: parquet.hadoop.codec.CodecConfig: Compression set to false
29/06/2015 4:58:36 PM INFO: parquet.hadoop.codec.CodecConfig: Compression: UNCOMPRESSED
29/06/2015 4:58:36 PM INFO: parquet.hadoop.ParquetOutputFormat: Parquet block size to 134217728
29/06/2015 4:58:36 PM INFO: parquet.hadoop.ParquetOutputFormat: Parquet page size to 1048576
29/06/2015 4:58:36 PM INFO: parquet.hadoop.ParquetOutputFormat: Parquet dictionary page size to 1048576
29/06/2015 4:58:36 PM INFO: parquet.hadoop.ParquetOutputFormat: Dictionary is on
29/06/2015 4:58:36 PM INFO: parquet.hadoop.ParquetOutputFormat: Validation is off
29/06/2015 4:58:36 PM INFO: parquet.hadoop.ParquetOutputFormat: Writer version is: PARQUET_1_0
29/06/2015 4:58:37 PM INFO: parquet.hadoop.InternalParquetRecordWriter: Flushing mem columnStore to file. allocated memory: 80,530,569
29/06/2015 4:59:29 PM INFO: parquet.hadoop.ParquetFileReader: Initiating action with parallelism: 5
15/06/29 16:59:29 INFO flow.Flow: [] shutdown hook calling stop on flow
15/06/29 16:59:29 INFO flow.Flow: [] stopping all jobs
15/06/29 16:59:29 INFO flow.FlowStep: [] stopping: (1/1) ...f5-4bcb-a24a-97ba74633b81
15/06/29 16:59:29 INFO flow.Flow: [] stopped all jobs
Exited job au.com.cba.omnia.etl.commsee.car.CseCcaAppExportExecution (0.1.0-20150629065246-fad9259) at Mon Jun 29 16:59:34 AEST 2015 with status 255

**Comment by SajeevAr** [comment]
Since the job is expecting an empty pipe in this case, as a work around `TypedPipe.empty` is used to get an empty TypedPipe.

**Comment by SajeevAr** [comment]
Please find the below exception:

15/06/29 16:59:24 INFO util.Version: Concurrent, Inc - Cascading 2.5.5
15/06/29 16:59:24 INFO flow.Flow: [] starting
15/06/29 16:59:24 INFO flow.Flow: []  source: Hfs["ParquetScroogeScheme[[UNKNOWN]->[ALL]]"]["<input_path>"]
15/06/29 16:59:24 INFO flow.Flow: []  sink: Hfs["TextDelimited[[0]]"]["/tmp/ST_128_08_CCA_APP1cb623dc-c1f5-4bcb-a24a-97ba74633b81"]
15/06/29 16:59:24 INFO flow.Flow: []  parallel execution is enabled: true
15/06/29 16:59:24 INFO flow.Flow: []  starting jobs: 1
15/06/29 16:59:24 INFO flow.Flow: []  allocating threads: 1
15/06/29 16:59:24 INFO flow.FlowStep: [] starting step: (1/1) ...f5-4bcb-a24a-97ba74633b81
15/06/29 16:59:29 INFO mapred.FileInputFormat: Total input paths to process : 0
15/06/29 16:59:29 INFO mapred.JobClient: Cleaning up the staging area 
15/06/29 16:59:29 INFO flow.Flow: [] stopping all jobs
15/06/29 16:59:29 INFO flow.FlowStep: [] stopping: (1/1) ...f5-4bcb-a24a-97ba74633b81
15/06/29 16:59:29 INFO flow.Flow: [] stopped all jobs
15/06/29 16:59:29 ERROR car.CseCcaAppExportExecution$: error running execution
java.lang.NullPointerException
	at parquet.hadoop.ParquetInputFormat.getSplits(ParquetInputFormat.java:430)
	at parquet.hadoop.mapred.DeprecatedParquetInputFormat.getSplits(DeprecatedParquetInputFormat.java:48)
	at cascading.tap.hadoop.io.MultiInputFormat.getSplits(MultiInputFormat.java:200)
	at cascading.tap.hadoop.io.MultiInputFormat.getSplits(MultiInputFormat.java:134)
	at org.apache.hadoop.mapred.JobClient.writeOldSplits(JobClient.java:1134)
	at org.apache.hadoop.mapred.JobClient.writeSplits(JobClient.java:1126)
	at org.apache.hadoop.mapred.JobClient.access$600(JobClient.java:178)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:1023)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:976)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1642)
	at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:976)
	at org.apache.hadoop.mapred.JobClient.submitJob(JobClient.java:950)
	at cascading.flow.hadoop.planner.HadoopFlowStepJob.internalNonBlockingStart(HadoopFlowStepJob.java:107)
	at cascading.flow.planner.FlowStepJob.blockOnJob(FlowStepJob.java:196)
	at cascading.flow.planner.FlowStepJob.start(FlowStepJob.java:149)
	at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:124)
	at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:43)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
29/06/2015 4:58:36 PM INFO: parquet.hadoop.codec.CodecConfig: Compression set to false
29/06/2015 4:58:36 PM INFO: parquet.hadoop.codec.CodecConfig: Compression: UNCOMPRESSED
29/06/2015 4:58:36 PM INFO: parquet.hadoop.ParquetOutputFormat: Parquet block size to 134217728
29/06/2015 4:58:36 PM INFO: parquet.hadoop.ParquetOutputFormat: Parquet page size to 1048576
29/06/2015 4:58:36 PM INFO: parquet.hadoop.ParquetOutputFormat: Parquet dictionary page size to 1048576
29/06/2015 4:58:36 PM INFO: parquet.hadoop.ParquetOutputFormat: Dictionary is on
29/06/2015 4:58:36 PM INFO: parquet.hadoop.ParquetOutputFormat: Validation is off
29/06/2015 4:58:36 PM INFO: parquet.hadoop.ParquetOutputFormat: Writer version is: PARQUET_1_0
29/06/2015 4:58:37 PM INFO: parquet.hadoop.InternalParquetRecordWriter: Flushing mem columnStore to file. allocated memory: 80,530,569
29/06/2015 4:59:29 PM INFO: parquet.hadoop.ParquetFileReader: Initiating action with parallelism: 5
15/06/29 16:59:29 INFO flow.Flow: [] shutdown hook calling stop on flow
15/06/29 16:59:29 INFO flow.Flow: [] stopping all jobs
15/06/29 16:59:29 INFO flow.FlowStep: [] stopping: (1/1) ...f5-4bcb-a24a-97ba74633b81
15/06/29 16:59:29 INFO flow.Flow: [] stopped all jobs
Exited job au.com.cba.omnia.etl.commsee.car.CseCcaAppExportExecution (0.1.0-20150629065246-fad9259) at Mon Jun 29 16:59:34 AEST 2015 with status 255

**Comment by rowandavies** [comment]
@SajeevAr Exception messages look better when in triple quotes, so I edited your comment above.

**Comment by rowandavies** [comment]
@SajeevAr I think you showed me some minimal code that produces this exception, and that demonstrates that changing from an empty input folder to an `EmptyPipe` works around the issue.  Can you post that code here?   Or, if it seems more appropriate, give the name of a stash repo and branch where it can be found.

**Comment by SajeevAr** [comment]
@rowandavies The code is available in master branch of stash repo "etl.commsee-car" (CarExportExecution.scala). Just to clarify - this is not a work around for this problem in general, but its a different approach used for a particular use case. Here a condition is added to check if the input directory is empty and if it is empty, `TypedPipe.empty` is used, instead of reading the empty directory using ParquetScroogeSource.

**Comment by rowandavies** [comment]
This seems to be related to https://issues.apache.org/jira/browse/PARQUET-294 which is unresolved.
