### ISSUE TITLE
Hive.queries throwing OutOfMemoryError exception while querying from empty partition in parquet table

### ISSUE THREAD

**Issue by SajeevAr** [CommBank/ebenezer#122]
The job that runs a hive queries on a parquet table using Hive.queries failed with the following exception. But while rerunning the same job it got succeeded. It is hard to replicate this issue as it happens rarely and most of the cases it running successfully. Also, so far couldn't replicate this issue while running the same query from Hive terminal.
The issue was seen while querying from an empty partition of parquet table and the total number of columns in the table was 54. 

Please find the exception below:

""" 15/08/07 10:12:22 INFO ql.Driver: Starting command: SELECT COUNT(*) FROM <table_name> where year=2015 and month=07 and day=23
15/08/07 10:12:22 INFO ql.Driver: Total jobs = 1
15/08/07 10:12:22 INFO log.PerfLogger: </PERFLOG method=TimeToSubmit start=1438906335564 end=1438906342756 duration=7192 from=org.apache.hadoop.hive.ql.Driver>
15/08/07 10:12:22 INFO log.PerfLogger: <PERFLOG method=runTasks from=org.apache.hadoop.hive.ql.Driver>
15/08/07 10:12:22 INFO log.PerfLogger: <PERFLOG method=task.MAPRED.Stage-1 from=org.apache.hadoop.hive.ql.Driver>
15/08/07 10:12:22 INFO ql.Driver: Launching Job 1 out of 1
15/08/07 10:12:22 INFO exec.Task: Number of reduce tasks determined at compile time: 1
15/08/07 10:12:22 INFO exec.Task: In order to change the average load for a reducer (in bytes):
15/08/07 10:12:22 INFO exec.Task:   set hive.exec.reducers.bytes.per.reducer=<number>
15/08/07 10:12:22 INFO exec.Task: In order to limit the maximum number of reducers:
15/08/07 10:12:22 INFO exec.Task:   set hive.exec.reducers.max=<number>
15/08/07 10:12:22 INFO exec.Task: In order to set a constant number of reducers:
15/08/07 10:12:22 INFO exec.Task:   set mapreduce.job.reduces=<number>
15/08/07 10:12:22 INFO ql.Context: New scratch dir is hdfs://nameservice1/tmp/<user>/hive_2015-08-07_10-12-15_732_2037660631944621553-1
15/08/07 10:12:22 INFO mr.ExecDriver: Using org.apache.hadoop.hive.ql.io.CombineHiveInputFormat
15/08/07 10:12:22 INFO exec.Utilities: Processing alias cse_cca_app_transformation
15/08/07 10:12:22 INFO exec.Utilities: Adding input file <path>
15/08/07 10:12:22 INFO exec.Utilities: Content Summary not cached for <path>
15/08/07 10:12:22 INFO parquet.MapredParquetOutputFormat: creating new record writer...org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat@6905d492
15/08/07 10:12:22 INFO write.ParquetRecordWriterWrapper: creating real writer to write at hdfs://nameservice1/tmp/<user>/hive_2015-08-07_10-12-15_732_2037660631944621553-1/-mr-10003/0/emptyFile
15/08/07 10:12:27 INFO write.ParquetRecordWriterWrapper: real writer: parquet.hadoop.ParquetRecordWriter@5864e248
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
15/08/07 10:13:06 INFO retry.RetryInvocationHandler: Exception while invoking addBlock of class ClientNamenodeProtocolTranslatorPB over <>. Trying to fail over immediately.
15/08/07 10:13:12 WARN hdfs.DFSClient: DataStreamer Exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.io.BufferedReader.<init>(BufferedReader.java:98)
	at java.io.BufferedReader.<init>(BufferedReader.java:109)
	at java.io.LineNumberReader.<init>(LineNumberReader.java:72)
	at org.apache.log4j.DefaultThrowableRenderer.render(DefaultThrowableRenderer.java:64)
	at org.apache.log4j.spi.ThrowableInformation.getThrowableStrRep(ThrowableInformation.java:87)
	at org.apache.log4j.spi.LoggingEvent.getThrowableStrRep(LoggingEvent.java:413)
	at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:313)
	at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at org.apache.commons.logging.impl.Log4JLogger.info(Log4JLogger.java:187)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:140)
	at com.sun.proxy.$Proxy15.addBlock(Unknown Source)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.locateFollowingBlock(DFSOutputStream.java:1473)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1290)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:536)
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.getReturnProtoType(ProtobufRpcEngine.java:261)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:226)
	at com.sun.proxy.$Proxy14.complete(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.complete(ClientNamenodeProtocolTranslatorPB.java:435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy15.complete(Unknown Source)
	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:2164)
	at org.apache.hadoop.hdfs.DFSOutputStream.close(DFSOutputStream.java:2148)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
	at parquet.hadoop.ParquetFileWriter.end(ParquetFileWriter.java:377)
	at parquet.hadoop.InternalParquetRecordWriter.close(InternalParquetRecordWriter.java:111)
	at parquet.hadoop.ParquetRecordWriter.close(ParquetRecordWriter.java:73)
	at org.apache.hadoop.hive.ql.io.parquet.write.ParquetRecordWriterWrapper.close(ParquetRecordWriterWrapper.java:66)
	at org.apache.hadoop.hive.ql.io.parquet.write.ParquetRecordWriterWrapper.close(ParquetRecordWriterWrapper.java:83)
	at org.apache.hadoop.hive.ql.exec.Utilities.createEmptyFile(Utilities.java:3068)
	at org.apache.hadoop.hive.ql.exec.Utilities.createDummyFileForEmptyPartition(Utilities.java:3093)
	at org.apache.hadoop.hive.ql.exec.Utilities.getInputPaths(Utilities.java:3016)
	at org.apache.hadoop.hive.ql.exec.mr.ExecDriver.execute(ExecDriver.java:369)
	at org.apache.hadoop.hive.ql.exec.mr.MapRedTask.execute(MapRedTask.java:136)
	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:153)
	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:85)
	at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1516)
	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1283)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1101)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:924)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:914)
FAILED: Execution Error, return code -101 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. GC overhead limit exceeded
15/08/07 10:13:13 ERROR ql.Driver: FAILED: Execution Error, return code -101 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. GC overhead limit exceeded """

**Comment by SajeevAr** [comment]
Please find the exception below:

``` 15/08/07 10:12:22 INFO ql.Driver: Starting command: SELECT COUNT(*) FROM <table_name> where year=2015 and month=07 and day=23
15/08/07 10:12:22 INFO ql.Driver: Total jobs = 1
15/08/07 10:12:22 INFO log.PerfLogger: </PERFLOG method=TimeToSubmit start=1438906335564 end=1438906342756 duration=7192 from=org.apache.hadoop.hive.ql.Driver>
15/08/07 10:12:22 INFO log.PerfLogger: <PERFLOG method=runTasks from=org.apache.hadoop.hive.ql.Driver>
15/08/07 10:12:22 INFO log.PerfLogger: <PERFLOG method=task.MAPRED.Stage-1 from=org.apache.hadoop.hive.ql.Driver>
15/08/07 10:12:22 INFO ql.Driver: Launching Job 1 out of 1
15/08/07 10:12:22 INFO exec.Task: Number of reduce tasks determined at compile time: 1
15/08/07 10:12:22 INFO exec.Task: In order to change the average load for a reducer (in bytes):
15/08/07 10:12:22 INFO exec.Task:   set hive.exec.reducers.bytes.per.reducer=<number>
15/08/07 10:12:22 INFO exec.Task: In order to limit the maximum number of reducers:
15/08/07 10:12:22 INFO exec.Task:   set hive.exec.reducers.max=<number>
15/08/07 10:12:22 INFO exec.Task: In order to set a constant number of reducers:
15/08/07 10:12:22 INFO exec.Task:   set mapreduce.job.reduces=<number>
15/08/07 10:12:22 INFO ql.Context: New scratch dir is hdfs://nameservice1/tmp/<user>/hive_2015-08-07_10-12-15_732_2037660631944621553-1
15/08/07 10:12:22 INFO mr.ExecDriver: Using org.apache.hadoop.hive.ql.io.CombineHiveInputFormat
15/08/07 10:12:22 INFO exec.Utilities: Processing alias cse_cca_app_transformation
15/08/07 10:12:22 INFO exec.Utilities: Adding input file <path>
15/08/07 10:12:22 INFO exec.Utilities: Content Summary not cached for <path>
15/08/07 10:12:22 INFO parquet.MapredParquetOutputFormat: creating new record writer...org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat@6905d492
15/08/07 10:12:22 INFO write.ParquetRecordWriterWrapper: creating real writer to write at hdfs://nameservice1/tmp/<user>/hive_2015-08-07_10-12-15_732_2037660631944621553-1/-mr-10003/0/emptyFile
15/08/07 10:12:27 INFO write.ParquetRecordWriterWrapper: real writer: parquet.hadoop.ParquetRecordWriter@5864e248
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
15/08/07 10:13:06 INFO retry.RetryInvocationHandler: Exception while invoking addBlock of class ClientNamenodeProtocolTranslatorPB over <>. Trying to fail over immediately.
15/08/07 10:13:12 WARN hdfs.DFSClient: DataStreamer Exception
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.io.BufferedReader.<init>(BufferedReader.java:98)
	at java.io.BufferedReader.<init>(BufferedReader.java:109)
	at java.io.LineNumberReader.<init>(LineNumberReader.java:72)
	at org.apache.log4j.DefaultThrowableRenderer.render(DefaultThrowableRenderer.java:64)
	at org.apache.log4j.spi.ThrowableInformation.getThrowableStrRep(ThrowableInformation.java:87)
	at org.apache.log4j.spi.LoggingEvent.getThrowableStrRep(LoggingEvent.java:413)
	at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:313)
	at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at org.apache.commons.logging.impl.Log4JLogger.info(Log4JLogger.java:187)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:140)
	at com.sun.proxy.$Proxy15.addBlock(Unknown Source)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.locateFollowingBlock(DFSOutputStream.java:1473)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1290)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:536)
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.getReturnProtoType(ProtobufRpcEngine.java:261)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:226)
	at com.sun.proxy.$Proxy14.complete(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.complete(ClientNamenodeProtocolTranslatorPB.java:435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy15.complete(Unknown Source)
	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:2164)
	at org.apache.hadoop.hdfs.DFSOutputStream.close(DFSOutputStream.java:2148)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
	at parquet.hadoop.ParquetFileWriter.end(ParquetFileWriter.java:377)
	at parquet.hadoop.InternalParquetRecordWriter.close(InternalParquetRecordWriter.java:111)
	at parquet.hadoop.ParquetRecordWriter.close(ParquetRecordWriter.java:73)
	at org.apache.hadoop.hive.ql.io.parquet.write.ParquetRecordWriterWrapper.close(ParquetRecordWriterWrapper.java:66)
	at org.apache.hadoop.hive.ql.io.parquet.write.ParquetRecordWriterWrapper.close(ParquetRecordWriterWrapper.java:83)
	at org.apache.hadoop.hive.ql.exec.Utilities.createEmptyFile(Utilities.java:3068)
	at org.apache.hadoop.hive.ql.exec.Utilities.createDummyFileForEmptyPartition(Utilities.java:3093)
	at org.apache.hadoop.hive.ql.exec.Utilities.getInputPaths(Utilities.java:3016)
	at org.apache.hadoop.hive.ql.exec.mr.ExecDriver.execute(ExecDriver.java:369)
	at org.apache.hadoop.hive.ql.exec.mr.MapRedTask.execute(MapRedTask.java:136)
	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:153)
	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:85)
	at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1516)
	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1283)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1101)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:924)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:914)
FAILED: Execution Error, return code -101 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. GC overhead limit exceeded
15/08/07 10:13:13 ERROR ql.Driver: FAILED: Execution Error, return code -101 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. GC overhead limit exceeded ```

**Comment by jithinjohn** [comment]
@SajeevAr  we also faced this issue while trying to read from an empty partition. One solution is to increase  `HADOOP_CLIENT_OPTS`  and it worked for us. Please try `export HADOOP_CLIENT_OPTS="-Xmxvalue"` once and see how it goes.
