### ISSUE TITLE
Some task fail when writing to hive table

### ISSUE THREAD

**Issue by stephanh** [CommBank/ebenezer#34]
When writing to a hive table the overall job completes, however, some tasks fail saying that the table already exists. Before the job was started the table didn't exist and the table is created as part of the job.

```
cascading.CascadingException: java.io.IOException: AlreadyExistsException(message:Table by_date already exists)
	at cascading.tap.hive.HivePartitionTap$HivePartitionCollector.closeCollector(HivePartitionTap.java:88)
	at cascading.tap.partition.BasePartitionTap$PartitionCollector.close(BasePartitionTap.java:186)
	at cascading.flow.stream.SinkStage.cleanup(SinkStage.java:120)
	at cascading.flow.stream.StreamGraph.cleanup(StreamGraph.java:176)
	at cascading.flow.hadoop.FlowMapper.run(FlowMapper.java:149)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:417)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:332)
	at org.apache.hadoop.mapred.Child$4.run(Child.java:268)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:396)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1438)
	at org.apache.hadoop.mapred.Child.main(Child.java:262)
Caused by: java.io.IOException: AlreadyExistsException(message:Table by_date already exists)
	at cascading.tap.hive.HiveTap.createHiveTable(HiveTap.java:147)
	at cascading.tap.hive.HiveTap.registerPartition(HiveTap.java:285)
	at cascading.tap.hive.HivePartitionTap$HivePartitionCollector.closeCollector(HivePartitionTap.java:84)
	... 11 more
Caused by: AlreadyExistsException(message:Table by_date already exists)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_result$create_table_resultStandardScheme.read(ThriftHiveMetastore.java:20131)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_result$create_table_resultStandardScheme.read(ThriftHiveMetastore.java:20117)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_result.read(ThriftHiveMetastore.java:20043)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_create_table(ThriftHiveMetastore.java:732)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.create_table(ThriftHiveMetastore.java:719)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:432)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:74)
	at $Proxy22.createTable(Unknown Source)
	at cascading.tap.hive.HiveTap.createHiveTable(HiveTap.java:137)
	... 13 more
```

**Comment by vineethvarghese** [comment]
I don't think we have the problem anymore as we make the database and table from the client. Feel free to reopen if you still this as a problem.
