### ISSUE TITLE
Tests for Hive using CDH5 fail with MetaException

### ISSUE THREAD

**Issue by stephanh** [CommBank/ebenezer#81]
Under some circumstances when running unit tests using the Hive monad where we:
* Run a test using Hive
* Followed by a test using the `Hive.createTable` method zipped and then another Hive command
 
The execution fails with `MetaException(message:Metastore contains multiple versions)`.

###Sample code
```
 def pre = {
    executesOk(Execution.fromHive(Hive.query("SHOW DATABASES")))
  }

  def test = {
    val exec = for {
      r <- Execution.fromHive(Hive.createParquetTable[SimpleHive]("testa", "unpart", List.empty, None)) zip Execution.fromHive(Hive.createParquetTable[SimpleHive]("testb", "unpart", List.empty, None))
      s <- Execution.fromHive(Hive.query("SHOW DATABASES")).recoverWith { case _ => Execution.from(List("other")) }
      _ <- Execution.fromHive(Hive.query("USE testa"))
    } yield s
    executesSuccessfully(exec) must_== List("default", "testa", "testb")
  }
```

###Exceptions:
```
MetaException(message:Metastore contains multiple versions)
	at org.apache.hadoop.hive.metastore.ObjectStore.getMSchemaVersion(ObjectStore.java:6373)
	at org.apache.hadoop.hive.metastore.ObjectStore.getMetaStoreSchemaVersion(ObjectStore.java:6335)
	at org.apache.hadoop.hive.metastore.ObjectStore.checkSchema(ObjectStore.java:6294)
	at org.apache.hadoop.hive.metastore.ObjectStore.verifySchema(ObjectStore.java:6282)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.hive.metastore.RawStoreProxy.invoke(RawStoreProxy.java:108)
	at com.sun.proxy.$Proxy30.verifySchema(Unknown Source)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.getMS(HiveMetaStore.java:485)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.get_all_databases(HiveMetaStore.java:1035)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invoke(RetryingHMSHandler.java:106)
	at com.sun.proxy.$Proxy32.get_all_databases(Unknown Source)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getAllDatabases(HiveMetaStoreClient.java:848)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:90)
	at com.sun.proxy.$Proxy33.getAllDatabases(Unknown Source)
	at org.apache.hadoop.hive.ql.metadata.Hive.getAllDatabases(Hive.java:1121)
	at org.apache.hadoop.hive.ql.exec.DDLTask.showDatabases(DDLTask.java:2430)
	at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:363)
	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:153)
	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:85)
	at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1516)
	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1283)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1101)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:924)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:914)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anonfun$query$1.apply(Hive.scala:385)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anonfun$query$1.apply(Hive.scala:378)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive.run(Hive.scala:133)
	at au.com.cba.omnia.ebenezer.scrooge.hive.RichExecutionObject$$anonfun$fromHive$1$$anonfun$apply$76.apply(HiveSpec.scala:315)
	at au.com.cba.omnia.ebenezer.scrooge.hive.RichExecutionObject$$anonfun$fromHive$1$$anonfun$apply$76.apply(HiveSpec.scala:315)
	at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1$$anonfun$1.apply(Execution.scala:251)
	at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1$$anonfun$1.apply(Execution.scala:251)
	at scala.util.Try$.apply(Try.scala:161)
	at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1.apply(Execution.scala:251)
	at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1.apply(Execution.scala:250)
	at com.twitter.scalding.Execution$MapEvalCache.getOrElseInsert(Execution.scala:224)
	at com.twitter.scalding.Execution$FutureConst.runStats(Execution.scala:250)
	at com.twitter.scalding.Execution$FlatMapped$$anonfun$runStats$2$$anonfun$3.apply(Execution.scala:268)
	at com.twitter.scalding.Execution$FlatMapped$$anonfun$runStats$2$$anonfun$3.apply(Execution.scala:266)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

```
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. MetaException(message:Got exception: org.apache.hadoop.hive.metastore.api.MetaException Metastore contains multiple versions)
MetaException(message:Metastore contains multiple versions)
	at org.apache.hadoop.hive.metastore.ObjectStore.getMSchemaVersion(ObjectStore.java:6373)
	at org.apache.hadoop.hive.metastore.ObjectStore.getMetaStoreSchemaVersion(ObjectStore.java:6335)
	at org.apache.hadoop.hive.metastore.ObjectStore.checkSchema(ObjectStore.java:6294)
	at org.apache.hadoop.hive.metastore.ObjectStore.verifySchema(ObjectStore.java:6282)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.hive.metastore.RawStoreProxy.invoke(RawStoreProxy.java:108)
	at com.sun.proxy.$Proxy30.verifySchema(Unknown Source)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.getMS(HiveMetaStore.java:485)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.get_database(HiveMetaStore.java:805)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invoke(RetryingHMSHandler.java:106)
	at com.sun.proxy.$Proxy32.get_database(Unknown Source)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getDatabase(HiveMetaStoreClient.java:960)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:90)
	at com.sun.proxy.$Proxy33.getDatabase(Unknown Source)
	at org.apache.hadoop.hive.ql.metadata.Hive.getDatabase(Hive.java:1188)
	at org.apache.hadoop.hive.ql.metadata.Hive.databaseExists(Hive.java:1177)
	at org.apache.hadoop.hive.ql.exec.DDLTask.switchDatabase(DDLTask.java:4035)
	at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:269)
	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:153)
	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:85)
	at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1516)
	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1283)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1101)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:924)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:914)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anonfun$query$1.apply(Hive.scala:385)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anonfun$query$1.apply(Hive.scala:378)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive.run(Hive.scala:133)
	at au.com.cba.omnia.ebenezer.scrooge.hive.RichExecutionObject$$anonfun$fromHive$1$$anonfun$apply$76.apply(HiveSpec.scala:315)
	at au.com.cba.omnia.ebenezer.scrooge.hive.RichExecutionObject$$anonfun$fromHive$1$$anonfun$apply$76.apply(HiveSpec.scala:315)
	at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1$$anonfun$1.apply(Execution.scala:251)
	at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1$$anonfun$1.apply(Execution.scala:251)
	at scala.util.Try$.apply(Try.scala:161)
	at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1.apply(Execution.scala:251)
	at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1.apply(Execution.scala:250)
	at com.twitter.scalding.Execution$MapEvalCache.getOrElseInsert(Execution.scala:224)
	at com.twitter.scalding.Execution$FutureConst.runStats(Execution.scala:250)
	at com.twitter.scalding.Execution$FlatMapped$$anonfun$runStats$2$$anonfun$3.apply(Execution.scala:268)
	at com.twitter.scalding.Execution$FlatMapped$$anonfun$runStats$2$$anonfun$3.apply(Execution.scala:266)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:Metastore contains multiple versions)
	at org.apache.hadoop.hive.ql.metadata.Hive.getDatabase(Hive.java:1192)
	at org.apache.hadoop.hive.ql.metadata.Hive.databaseExists(Hive.java:1177)
	at org.apache.hadoop.hive.ql.exec.DDLTask.switchDatabase(DDLTask.java:4035)
	at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:269)
	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:153)
	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:85)
	at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1516)
	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1283)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1101)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:924)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:914)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anonfun$query$1.apply(Hive.scala:385)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anonfun$query$1.apply(Hive.scala:378)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive.run(Hive.scala:133)
	at au.com.cba.omnia.ebenezer.scrooge.hive.RichExecutionObject$$anonfun$fromHive$1$$anonfun$apply$76.apply(HiveSpec.scala:315)
	at au.com.cba.omnia.ebenezer.scrooge.hive.RichExecutionObject$$anonfun$fromHive$1$$anonfun$apply$76.apply(HiveSpec.scala:315)
	at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1$$anonfun$1.apply(Execution.scala:251)
	at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1$$anonfun$1.apply(Execution.scala:251)
	at scala.util.Try$.apply(Try.scala:161)
	at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1.apply(Execution.scala:251)
	at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1.apply(Execution.scala:250)
	at com.twitter.scalding.Execution$MapEvalCache.getOrElseInsert(Execution.scala:224)
	at com.twitter.scalding.Execution$FutureConst.runStats(Execution.scala:250)
	at com.twitter.scalding.Execution$FlatMapped$$anonfun$runStats$2$$anonfun$3.apply(Execution.scala:268)
	at com.twitter.scalding.Execution$FlatMapped$$anonfun$runStats$2$$anonfun$3.apply(Execution.scala:266)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: MetaException(message:Metastore contains multiple versions)
	at org.apache.hadoop.hive.metastore.ObjectStore.getMSchemaVersion(ObjectStore.java:6373)
	at org.apache.hadoop.hive.metastore.ObjectStore.getMetaStoreSchemaVersion(ObjectStore.java:6335)
	at org.apache.hadoop.hive.metastore.ObjectStore.checkSchema(ObjectStore.java:6294)
	at org.apache.hadoop.hive.metastore.ObjectStore.verifySchema(ObjectStore.java:6282)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.hive.metastore.RawStoreProxy.invoke(RawStoreProxy.java:108)
	at com.sun.proxy.$Proxy30.verifySchema(Unknown Source)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.getMS(HiveMetaStore.java:485)
	at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.get_database(HiveMetaStore.java:805)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invoke(RetryingHMSHandler.java:106)
	at com.sun.proxy.$Proxy32.get_database(Unknown Source)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getDatabase(HiveMetaStoreClient.java:960)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:90)
	at com.sun.proxy.$Proxy33.getDatabase(Unknown Source)
	at org.apache.hadoop.hive.ql.metadata.Hive.getDatabase(Hive.java:1188)
	... 33 more
```

**Comment by stephanh** [comment]
This seems to be caused when in the same JVM session we:
1. Instantiate a hive session for other tests
2. Run a test where the first hive operations are executed in parallel.

It seems that even though we change Hive databases between tests the subsequent hive databases don't get used or instantiated in the same way as the first one. When the parallel hive interactions run they both do some sort of instantiation that is not concurrency safe which then causes other operations to have problems.

This can be avoided by ensuring that a single threaded hive operation is run at the beginning of each test.

**Comment by stephanh** [comment]
This has been fixed by updating HiveSupport in Thermometer.
